server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 10000
  connection-timeout: 5000ms
  servlet:
    context-path: /freedom
### spring配置
spring:
  profiles:
    active: dev
  messages:
    encoding: UTF-8
  mvc:
    throw-exception-if-no-handler-found: true #出现错误时, 直接抛出异常
  resources:
    add-mappings: false  #不要为我们工程中的资源文件建立映射
  ## jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  ## 文件上传配置
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mybatis:
  type-aliases-package: com.freedom.*.model #各别项目不使用别名
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    #二级缓存全局设置，关于mybatis的二级缓存对于多个项目操作数据做缓存不和谐
    cache-enabled: false
    #当启用时，有延迟加载属性的对象在被调用时将会完全加载任意属性。否则，每种属性将会按需要加载
    aggressive-lazy-loading: true
    #指定 MyBatis 如何自动映射 数据基表的列 NONE：不隐射　PARTIAL:部分  FULL:全部
    auto-mapping-behavior: partial
    #这是默认的执行类型  （SIMPLE: 简单； REUSE: 执行器可能重复使用prepared statements语句；BATCH: 执行器可以重复执行语句和批量更新）
    default-executor-type: simple
    #使用驼峰命名法转换字段
    map-underscore-to-camel-case: true
    #设置本地缓存范围 session:就会有数据的共享  statement:语句范围 (这样就不会有数据的共享 )
    local-cache-scope: statement
    #设置但JDBC类型为空时,某些驱动程序 要指定值,default:OTHER，插入空值时不需要指定类型
    jdbc-type-for-null: null
    #日志
    log-prefix: dao.

#分页
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    offset-as-page-num: true
    row-bounds-with-count: true
    page-size-zero: true


# 项目配置
freedom:
  #druid
  druidUserName: admin  #管理员账号
  druidPassword: admin  #管理员密码
  allows: 127.0.0.1,127.0.0.2 #白名单
  deny: #黑名单多个,分割
  #Swagger
  swaggerEnable: true #是否开启
  swaggerPath: com.freedom #扫描路径
  swaggerTitle: 文档标题
  swaggerDescription: 文档描述
  swaggerServiceUrl: /freedom
  swaggerUserName: liberc
  swaggerUserUrl:
  swaggerUserEmail: 1135621750@qq.com
  swaggerVersion: 1.0
  #jwt
  jwtSecret: freedom
  jwtExpire: 600000
  jwtHeader: token
  # redis 是否开启
  redisOpen: false
  # 本地文件上传路径
  file-upload-path: upload #文件上传路径在freedom路径下的文件路径
  token-name: Authorization